apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service-sa
  annotations:
    azure.workload.identity/client-id: "<MANAGED_IDENTITY_CLIENT_ID>"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  annotations:
    azure.workload.identity/client-id: "<PAYMENT_MANAGED_IDENTITY_CLIENT_ID>"
automountServiceAccountToken: true