apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: catalog-service-sa
      containers:
        - name: catalog-service
          env:
            - name: CATALOG_BACKEND
              value: "postgres"

            - name: PG_HOST
              value: "<POSTGRES_SERVER_NAME>.postgres.database.azure.com"
            - name: PG_DATABASE
              value: "catalog"
            - name: PG_USER
              value: "<CATALOG_MANAGED_IDENTITY_NAME>"

            - name: COSMOS_ENDPOINT
              value: "https://<your-cosmos-account>.documents.azure.com:443/"