apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - payment-keyvault.yaml

components:
  - ../../components/workload-identity
  - ../../components/network-policies

patches:
#   - path: email-service-patch.yaml
#     target:
#       kind: Deployment
#       name: email-service
  - path: catalog-service-patch.yaml
    target:
      kind: Deployment
      name: catalog-service
  - path: payment-service-patch.yaml
    target:
      kind: Deployment
      name: payment-service
  - path: payment-keyvault-patch.yaml
    target:
      kind: Deployment
      name: payment-service