apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "<PAYMENT_MANAGED_IDENTITY_CLIENT_ID>"
    keyvaultName: "<KEY_VAULT_NAME>"
    objects: |
      array:
        - |
          objectName: stripe-secret-key
          objectType: secret
    tenantID: "<TENANT_ID>"
  secretObjects:
    - secretName: payment-service-secrets
      type: Opaque
      data:
        - objectName: stripe-secret-key
          key: stripe-secret-key