apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: cart-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: cart-service-secrets
                  key: redis-addr
          livenessProbe:
            grpc:
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            grpc:
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
