apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cart-service-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cart-service-secrets"]
    verbs: ["get", "watch"]