apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      serviceAccountName: shipping-service-sa
      containers:
        - name: shipping-service
          image: shipping-service:latest
          ports:
            - containerPort: 5004
          livenessProbe:
            grpc:
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            grpc:
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 10
