apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-recommendation-ingress
spec:
  podSelector:
    matchLabels:
      app: recommendation-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
        - podSelector:
            matchLabels:
              app: envoy
      ports:
        - port: 5007