apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deny-all.yaml
  - allow-cart-ingress.yaml
  - allow-catalog-ingress.yaml
  - allow-currency-ingress.yaml
  - allow-email-ingress.yaml
  - allow-payment-ingress.yaml
  - allow-shipping-ingress.yaml
  - allow-recommendation-ingress.yaml
  - allow-checkout-ingress.yaml
  - allow-envoy-ingress.yaml